# 2026 Fantasy Life Draft Picks
# Generated from Fantasy_Life_Draft_Board.xlsx

PLAYERS = [
    "Tim", "Wu", "Jens", "Todd", "Mitchell", "Shep",
    "Theo", "Feder", "Fryar", "Korch", "Molmen", "Jamzee", "Buckley"
]

DRAFT_PICKS_2026 = {
    "NFL": {
        "Tim": "Seattle Seahawks",
        "Wu": "Baltimore Ravens",
        "Jens": "Buffalo Bills",
        "Todd": "San Francisco 49ers",
        "Mitchell": "Los Angeles Rams",
        "Shep": "Kansas City Chiefs",
        "Theo": "Indianapolis Colts",
        "Feder": "New England Patriots",
        "Fryar": "Green Bay Packers",
        "Korch": "Philadelphia Eagles",
        "Molmen": "Denver Broncos",
        "Jamzee": "Detroit Lions",
        "Buckley": "Tampa Bay Buccaneers",
    },
    "NBA": {
        "Tim": "Denver Nuggets",
        "Wu": "San Antonio Spurs",
        "Jens": "Cleveland Cavaliers",
        "Todd": "Minnesota Timberwolves",
        "Mitchell": "Golden State Warriors",
        "Shep": "Boston Celtics",
        "Theo": "Los Angeles Lakers",
        "Feder": "Oklahoma City Thunder",
        "Fryar": "Los Angeles Clippers",
        "Korch": "Houston Rockets",
        "Molmen": "Milwaukee Bucks",
        "Jamzee": "Orlando Magic",
        "Buckley": "New York Knicks",
    },
    "MLB": {
        "Tim": "Chicago Cubs",
        "Wu": "Los Angeles Dodgers",
        "Jens": "New York Yankees",
        "Todd": "Atlanta Braves",
        "Mitchell": "Philadelphia Phillies",
        "Shep": "Houston Astros",
        "Theo": "San Diego Padres",
        "Feder": "New York Mets",
        "Fryar": "Cleveland Guardians",
        "Korch": "Toronto Blue Jays",
        "Molmen": "Texas Rangers",
        "Jamzee": "Seattle Mariners",
        "Buckley": "Milwaukee Brewers",
    },
    "NHL": {
        "Tim": "Vegas Golden Knights",
        "Wu": "New Jersey Devils",
        "Jens": "Toronto Maple Leafs",
        "Todd": "Florida Panthers",
        "Mitchell": "Dallas Stars",
        "Shep": "Boston Bruins",
        "Theo": "Detroit Red Wings",
        "Feder": "Washington Capitals",
        "Fryar": "Tampa Bay Lightning",
        "Korch": "Colorado Avalanche",
        "Molmen": "New York Rangers",
        "Jamzee": "Carolina Hurricanes",
        "Buckley": "Edmonton Oilers",
    },
    "NCAAF": {
        "Tim": "BYU",
        "Wu": "Miami",
        "Jens": "Georgia Tech",
        "Todd": "Ole Miss",
        "Mitchell": "Ohio State",
        "Shep": "Michigan",
        "Theo": "Georgia",
        "Feder": "Notre Dame",
        "Fryar": "Texas A&M",
        "Korch": "Indiana",
        "Molmen": "Texas Tech",
        "Jamzee": "Alabama",
        "Buckley": "Oregon",
    },
    "NCAAB": {
        "Tim": "St. John's",
        "Wu": "Florida",
        "Jens": "Duke",
        "Todd": "UCLA",
        "Mitchell": "Alabama",
        "Shep": "Kansas",
        "Theo": "Houston",
        "Feder": "Kentucky",
        "Fryar": "UConn",
        "Korch": "Purdue",
        "Molmen": "North Carolina",
        "Jamzee": "Michigan",
        "Buckley": "Louisville",
    },
    "Tennis": {
        "Tim": "Madison Keys",
        "Wu": "Coco Gauff",
        "Jens": "Jasmine Paolini",
        "Todd": "Carlos Alcaraz",
        "Mitchell": "Taylor Fritz",
        "Shep": "Novak Djokovic",
        "Theo": "Alexander Zverev",
        "Feder": "Iga Swiatek",
        "Fryar": "Aryna Sabalenka",
        "Korch": "Jessica Pegula",
        "Molmen": "Daniil Medvedev",
        "Jamzee": "Amanda Anisimova",
        "Buckley": "Jannik Sinner",
    },
    "Golf": {
        "Tim": "Xander Schauffele",
        "Wu": "Scottie Scheffler",
        "Jens": "Russell Henley",
        "Todd": "Patrick Cantlay",
        "Mitchell": "J.J. Spaun",
        "Shep": "Jon Rahm",
        "Theo": "Justin Thomas",
        "Feder": "Bryson DeChambeau",
        "Fryar": "Viktor Hovland",
        "Korch": "Tommy Fleetwood",
        "Molmen": "Rory McIlroy",
        "Jamzee": "Ludvig Aberg",
        "Buckley": "Collin Morikawa",
    },
    "NASCAR": {
        "Tim": "Bubba Wallace",
        "Wu": "Christopher Bell",
        "Jens": "Chase Briscoe",
        "Todd": "Chase Elliott",
        "Mitchell": "Shane van Gisbergen",
        "Shep": "Daniel Suarez",
        "Theo": "Denny Hamlin",
        "Feder": "Tyler Reddick",
        "Fryar": "Ryan Blaney",
        "Korch": "William Byron",
        "Molmen": "Kyle Larson",
        "Jamzee": "Joey Logano",
        "Buckley": "Ross Chastain",
    },
    "MLS": {
        "Tim": "Charlotte FC",
        "Wu": "Minnesota United",
        "Jens": "San Diego FC",
        "Todd": "New York Red Bulls",
        "Mitchell": "Philadelphia Union",
        "Shep": "Orlando City",
        "Theo": "Inter Miami",
        "Feder": "Vancouver Whitecaps",
        "Fryar": "Columbus Crew",
        "Korch": "FC Cincinnati",
        "Molmen": "LA Galaxy",
        "Jamzee": "Seattle Sounders",
        "Buckley": "LAFC",
    },
    "Actor": {
        "Tim": "Sean Penn",
        "Wu": "Wagner Moura",
        "Jens": "George Clooney",
        "Todd": "Leonardo DiCaprio",
        "Mitchell": "Pedro Pascal",
        "Shep": "Jeremy Allen White",
        "Theo": "Dwayne Johnson",
        "Feder": "Tom Holland",
        "Fryar": "Chris Hemsworth",
        "Korch": "Jon Bernthal",
        "Molmen": "Matt Damon",
        "Jamzee": "Timothee Chalamet",
        "Buckley": "Robert Pattinson",
    },
    "Actress": {
        "Tim": "Ariana Grande",
        "Wu": "Zendaya",
        "Jens": "Amanda Seyfried",
        "Todd": "Teyana Taylor",
        "Mitchell": "Charlize Theron",
        "Shep": "Tessa Thompson",
        "Theo": "Sydney Sweeney",
        "Feder": "Cynthia Erivo",
        "Fryar": "Florence Pugh",
        "Korch": "Anne Hathaway",
        "Molmen": "Jessie Buckley",
        "Jamzee": "Emma Stone",
        "Buckley": "Anya Taylor-Joy",
    },
    "Musician": {
        "Tim": "Kendrick Lamar",
        "Wu": "FKA Twigs",
        "Jens": "Sabrina Carpenter",
        "Todd": "Olivia Rodrigo",
        "Mitchell": "Bad Bunny",
        "Shep": "Drake",
        "Theo": "BTS",
        "Feder": "Lady Gaga",
        "Fryar": "Justin Bieber",
        "Korch": "SZA",
        "Molmen": "Taylor Swift",
        "Jamzee": "The Weeknd",
        "Buckley": "Beyonce",
    },
    "Country": {
        "Tim": "Netherlands",
        "Wu": "United States",
        "Jens": "Germany",
        "Todd": "Guinea",
        "Mitchell": "South Sudan",
        "Shep": "France",
        "Theo": "Switzerland",
        "Feder": "Brazil",
        "Fryar": "Norway",
        "Korch": "Guyana",
        "Molmen": "Argentina",
        "Jamzee": "Spain",
        "Buckley": "Canada",
    },
    "Stock": {
        "Tim":     {"ticker": "COIN", "direction": "L"},
        "Wu":      {"ticker": "LULU", "direction": "L"},
        "Jens":    {"ticker": "SOFI", "direction": "L"},
        "Todd":    {"ticker": "NVDA", "direction": "L"},
        "Mitchell":{"ticker": "CVNA", "direction": "S"},
        "Shep":    {"ticker": "TSLA", "direction": "S"},
        "Theo":    {"ticker": "CMG",  "direction": "L"},
        "Feder":   {"ticker": "PLTR", "direction": "L"},
        "Fryar":   {"ticker": "AVGO", "direction": "L"},
        "Korch":   {"ticker": "SMCI", "direction": "L"},
        "Molmen":  {"ticker": "TTWO", "direction": "L"},
        "Jamzee":  {"ticker": "INTC", "direction": "L"},
        "Buckley": {"ticker": "NEE",  "direction": "L"},
    },
}

# Tennis gender classification (affects adjusted ranking per Amendment 7.4)
# Women get rank + 0.5 applied before sorting
TENNIS_GENDER = {
    "Madison Keys": "F",
    "Coco Gauff": "F",
    "Jasmine Paolini": "F",
    "Carlos Alcaraz": "M",
    "Taylor Fritz": "M",
    "Novak Djokovic": "M",
    "Alexander Zverev": "M",
    "Iga Swiatek": "F",
    "Aryna Sabalenka": "F",
    "Jessica Pegula": "F",
    "Daniil Medvedev": "M",
    "Amanda Anisimova": "F",
    "Jannik Sinner": "M",
}

if __name__ == "__main__":
    print("2026 Draft Picks loaded successfully")
    for cat, picks in DRAFT_PICKS_2026.items():
        print(f"  {cat}: {len(picks)} players")
